"""Added models

Revision ID: 743a7d46f2b0
Revises: 16b92d6eb96c
Create Date: 2023-09-07 23:02:55.705423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '743a7d46f2b0'
down_revision: Union[str, None] = '16b92d6eb96c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_of_relationship', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationships_type_of_relationship'), 'relationships', ['type_of_relationship'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_name'), 'people', ['name'], unique=False)
    op.create_table('connections',
    sa.Column('individual1_id', sa.Integer(), nullable=False),
    sa.Column('individual2_id', sa.Integer(), nullable=False),
    sa.Column('relationship_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['individual1_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['individual2_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationships.id'], ),
    sa.PrimaryKeyConstraint('individual1_id', 'individual2_id', 'relationship_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connections')
    op.drop_index(op.f('ix_people_name'), table_name='people')
    op.drop_table('people')
    op.drop_table('users')
    op.drop_index(op.f('ix_relationships_type_of_relationship'), table_name='relationships')
    op.drop_table('relationships')
    # ### end Alembic commands ###
