"""All tables

Revision ID: 65c6149a42b0
Revises: f37d7dc65c4c
Create Date: 2023-09-08 12:27:18.506947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65c6149a42b0'
down_revision: Union[str, None] = 'f37d7dc65c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('user_relationship', sa.String(), nullable=True))
    op.drop_column('people', 'user_relashionship')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('user_relashionship', sa.VARCHAR(), nullable=True))
    op.drop_column('people', 'user_relationship')
    # ### end Alembic commands ###
