"""add to user

Revision ID: f00c35dd1a5c
Revises: 197591c1a995
Create Date: 2023-09-08 16:21:39.140439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f00c35dd1a5c'
down_revision: Union[str, None] = '197591c1a995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('user_relashionship', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'user_relashionship')
    # ### end Alembic commands ###
